#!/bin/csh

/ad/eng/opt/mentor/modelsim/modeltech/bin/vlib work

/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../rtl/RISC_V_Core.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../rtl/memory_hierarchy.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/src/fetch.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/src/fetch_pipe.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/src/decode.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/src/decode_pipe.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/src/stallControl.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/src/control_unit.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/src/execute.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/src/execute_pipe.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/src/memory.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/src/memory_pipe.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/src/writeback.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/L1cache.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/Lxcache.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/coherence_controller.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/main_memory_interface.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/src/regFile.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/src/ALU.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/one_hot_decoder.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/arbiter.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/main_memory.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/priority_encoder.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/bram.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/dual_port_ram.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/replacement_controller.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/fifo_arbiter.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/lru.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/empty_way_select.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/fifo.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/replacement_controller_lx.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../ip/seven_stage_pipeline_with_caches_and_main_memory/memory_hierarchy/lru_lx.v
/ad/eng/opt/mentor/modelsim/modeltech/bin/vlog ../../tb/tb_RISC_V_Core.v

/ad/eng/opt/mentor/modelsim/modeltech/bin/vsim -GPROGRAM=\"../../ip/seven_stage_pipeline_with_caches_and_main_memory/gcd.mem\" -voptargs=+acc work.tb_RISC_V_Core -do run_sim.tcl
